name: MongoDB CI Test

on: [pull_request]

jobs:
  test-mongodb:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug MongoDB connection
        run: |
          docker network ls
          docker ps -a
          docker inspect mongo
          nc -zv mongo 27017 || true
      - name: Check MongoDB shell
        run: mongosh --version

      - name: Wait for MongoDB to be ready
        run: |
          echo "Waiting for MongoDB service..."
          sleep 10
          for i in {1..30}; do
            if mongosh --host mongo --eval "db.runCommand({ ping: 1 })" > /dev/null 2>&1; then
              echo "MongoDB is ready!"
              exit 0
            fi
            echo "Waiting for MongoDB to start ($i/30)..."
            sleep 2
          done
          echo "MongoDB did not start in time."
          exit 1


      - name: Run MongoDB script
        run: mongosh "mongodb://mongo:27017/testdb" --file test_queries.js

